name: Check
on: push
jobs: 
  lint:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/chekout@v4
      - name: Install
        run: npm ci
      - name: Lint Tekshirish
        run: npm run lint